### ISSUE TITLE
It's difficult to learn what's going on in fancy-app expressions without knowing what fancy-app does

### ISSUE THREAD

**Issue by jackfirth** [samth/fancy-app#1]
Given the snippet:

``` racket
(map (+ 5 _) '(1 2 3 4 5))
```

There's no way to tell that the `fancy-app` module is responsible for making `(+ 5 _)` evaluate to a function. This isn't a problem for the person who _wrote_ the code, but it makes it difficult for someone to read it unless they know what fancy-app does. It may be useful to do something to make it easier to track down the behavior, but there's an argument for RTFM. Is there possibly a way to get DrRacket's syntax arrows to help?

(As an aside, thank you for this package, I hardly ever write racket code without it!)

**Comment by samth** [comment]
I could arrange to draw arrows, but what arrows do you want? `(+ 5 _)` doesn't have any subcomponents that are connected to each other.

Ultimately, the need to know this behavior is part of trickiness in implicit `#%app` -- in languages like Scala, where this is also available, it's just part of the built-in syntax in that language that everyone has to know. So this is a drawback, but I think it's an inevitable one.

**Comment by jackfirth** [comment]
A _really nice_ behavior would be if expressions containing an underscore upon mouseover showed a tooltip saying "using #%app from fancy-app", but I'm not sure how that would be possible and I'm relatively sure it would involve extending DrRacket to support it. Additionally I wouldn't know how DrRacket would know which expressions to show such information for, since the overridden app is used everywhere, not just in expressions with underscores.

Barring something like that, this does seem inevitable. An arrow for the underscore to fancy-app might help somewhat, but that would be misleading when it's used in other macros such as syntax-rules.

**Comment by samth** [comment]
If you have suggestions for better things to say in the tooltips, that would be great. These are just preliminary.
